export const studentsData = [
  {
    id: 1,
    name: "Vignesh R",
    role: "Full Stack Developer",
    college: "VIT Chennai",
    image: "https://i.pravatar.cc/300?img=1",
    cover: "https://picsum.photos/400/200?random=1",
    skills: ["React", "Next.js", "TypeScript"],
    projects: 12,
    blogs: 8,
    followers: 320,
    verified: true,
    online: true,
    link: "/students/1",
  },
  {
    id: 2,
    name: "Ananya S",
    role: "Frontend Developer",
    college: "MIT University",
    image: "https://i.pravatar.cc/300?img=5",
    cover: "https://picsum.photos/400/200?random=2",
    skills: ["React", "Tailwind", "Figma"],
    projects: 10,
    blogs: 6,
    followers: 280,
    verified: true,
    online: true,
    link: "/students/2",
  },
  {
    id: 3,
    name: "Karthik M",
    role: "Backend Developer",
    college: "PSG College",
    image: "https://i.pravatar.cc/300?img=8",
    cover: "https://picsum.photos/400/200?random=3",
    skills: ["Node.js", "Express", "MongoDB"],
    projects: 9,
    blogs: 7,
    followers: 250,
    verified: true,
    online: true,
    link: "/students/3",
  },
  {
    id: 4,
    name: "Priya Sharma",
    role: "UI/UX Designer",
    college: "SRM Institute of Science and Technology",
    image: "https://i.pravatar.cc/300?img=20",
    cover: "https://picsum.photos/400/200?random=4",
    skills: ["Figma", "Adobe XD", "UI Design"],
    projects: 14,
    blogs: 5,
    followers: 410,
    verified: true,
    online: false,
    link: "/students/4",
  },
  {
    id: 5,
    name: "Arjun Kumar",
    role: "Machine Learning Engineer",
    college: "Anna University",
    image: "https://i.pravatar.cc/300?img=21",
    cover: "https://picsum.photos/400/200?random=5",
    skills: ["Python", "TensorFlow", "Pandas"],
    projects: 18,
    blogs: 9,
    followers: 560,
    verified: true,
    online: true,
    link: "/students/5",
  },
  {
    id: 6,
    name: "Sneha Reddy",
    role: "Mobile App Developer",
    college: "Amrita Vishwa Vidyapeetham",
    image: "https://i.pravatar.cc/300?img=22",
    cover: "https://picsum.photos/400/200?random=6",
    skills: ["Flutter", "Dart", "Firebase"],
    projects: 11,
    blogs: 4,
    followers: 295,
    verified: true,
    online: true,
    link: "/students/6",
  },
  {
    id: 7,
    name: "Rahul Verma",
    role: "DevOps Engineer",
    college: "NIT Trichy",
    image: "https://i.pravatar.cc/300?img=23",
    cover: "https://picsum.photos/400/200?random=7",
    skills: ["Docker", "AWS", "Kubernetes"],
    projects: 15,
    blogs: 10,
    followers: 480,
    verified: true,
    online: false,
    link: "/students/7",
  },
  {
    id: 8,
    name: "Meera Nair",
    role: "Cybersecurity Analyst",
    college: "CUSAT",
    image: "https://i.pravatar.cc/300?img=24",
    cover: "https://picsum.photos/400/200?random=8",
    skills: ["Ethical Hacking", "Linux", "Network Security"],
    projects: 13,
    blogs: 7,
    followers: 365,
    verified: true,
    online: true,
    link: "/students/8",
  },
  {
    id: 9,
    name: "Akash Patel",
    role: "Cloud Engineer",
    college: "IIT Gandhinagar",
    image: "https://i.pravatar.cc/300?img=25",
    cover: "https://picsum.photos/400/200?random=9",
    skills: ["Azure", "AWS", "Terraform"],
    projects: 17,
    blogs: 6,
    followers: 520,
    verified: true,
    online: true,
    link: "/students/9",
  },
  {
    id: 10,
    name: "Divya Menon",
    role: "Data Scientist",
    college: "Manipal University",
    image: "https://i.pravatar.cc/300?img=26",
    cover: "https://picsum.photos/400/200?random=10",
    skills: ["Python", "Scikit-Learn", "SQL"],
    projects: 16,
    blogs: 8,
    followers: 470,
    verified: true,
    online: false,
    link: "/students/10",
  },
  {
    id: 11,
    name: "Harish Babu",
    role: "Blockchain Developer",
    college: "SASTRA University",
    image: "https://i.pravatar.cc/300?img=27",
    cover: "https://picsum.photos/400/200?random=11",
    skills: ["Solidity", "Web3", "Ethereum"],
    projects: 12,
    blogs: 3,
    followers: 330,
    verified: true,
    online: true,
    link: "/students/11",
  },
  {
    id: 12,
    name: "Keerthana Ravi",
    role: "AI Engineer",
    college: "PSG College of Technology",
    image: "https://i.pravatar.cc/300?img=28",
    cover: "https://picsum.photos/400/200?random=12",
    skills: ["PyTorch", "LLMs", "Computer Vision"],
    projects: 19,
    blogs: 12,
    followers: 640,
    verified: true,
    online: true,
    link: "/students/12",
  },
  {
    id: 13,
    name: "Nikhil Joshi",
    role: "Software Engineer",
    college: "BITS Pilani",
    image: "https://i.pravatar.cc/300?img=29",
    cover: "https://picsum.photos/400/200?random=13",
    skills: ["Java", "Spring Boot", "MySQL"],
    projects: 20,
    blogs: 11,
    followers: 710,
    verified: true,
    online: false,
    link: "/students/13",
  },
];